
// This file is generated by Firebase Studio.
"use client";

import type { FC } from 'react';
import { useState, useEffect } from 'react';
import ProviderCard from './ProviderCard';
import type { ServiceProvider, Location as UserLocationType } from '@/types';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { SearchX, Loader2, ListFilter, MapPinned } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';

interface ProviderListProps {
  userLocation: UserLocationType | null;
  issueType: string;
  onSelectProvider: (provider: ServiceProvider) => void;
  staticProviders?: ServiceProvider[]; 
  isLoading?: boolean; // Add isLoading prop
}

function calculateDistance(loc1: UserLocationType, loc2: UserLocationType): number {
  const R = 6371; // Radius of the Earth in km
  const dLat = (loc2.lat - loc1.lat) * Math.PI / 180;
  const dLng = (loc2.lng - loc1.lng) * Math.PI / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(loc1.lat * Math.PI / 180) * Math.cos(loc2.lat * Math.PI / 180) *
    Math.sin(dLng / 2) * Math.sin(dLng / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

const ProviderList: FC<ProviderListProps> = ({ userLocation, issueType, onSelectProvider, staticProviders, isLoading = false }) => {
  const [allProviders, setAllProviders] = useState<ServiceProvider[]>(staticProviders || []);
  const [displayedProviders, setDisplayedProviders] = useState<ServiceProvider[]>([]);
  const [noSpecificMatch, setNoSpecificMatch] = useState(false);

  useEffect(() => {
    setAllProviders(staticProviders || []);
  }, [staticProviders]);


  useEffect(() => {
    if (isLoading) return; 

    setNoSpecificMatch(false);
    let primaryFilteredProviders = [...allProviders]; 
      
    if (issueType && issueType.trim() !== "") {
      const lowerIssueType = issueType.toLowerCase();
      primaryFilteredProviders = allProviders.filter(p => 
        Array.isArray(p.servicesOffered) && p.servicesOffered.some(service => 
          service.toLowerCase().includes(lowerIssueType) || 
          lowerIssueType.includes(service.toLowerCase()) 
        )
      );
    }
    
    if (userLocation) {
      primaryFilteredProviders = primaryFilteredProviders.map(p => ({
        ...p,
        distanceKm: calculateDistance(userLocation, p.currentLocation)
      })).sort((a,b) => (a.distanceKm ?? Infinity) - (b.distanceKm ?? Infinity));
    } else {
        primaryFilteredProviders = primaryFilteredProviders.map(p => ({ ...p, distanceKm: undefined })).sort((a,b) => a.etaMinutes - b.etaMinutes);
    }

    if (primaryFilteredProviders.length > 0) {
      setDisplayedProviders(primaryFilteredProviders);
    } else {
      setNoSpecificMatch(true);
      let fallbackProviders = [...allProviders].map(p => userLocation ? ({...p, distanceKm: calculateDistance(userLocation, p.currentLocation)}) : ({...p, distanceKm: undefined}));
      if (userLocation) {
          fallbackProviders.sort((a,b) => (a.distanceKm ?? Infinity) - (b.distanceKm ?? Infinity));
      } else {
          fallbackProviders.sort((a,b) => a.etaMinutes - b.etaMinutes);
      }
      setDisplayedProviders(fallbackProviders);
    }
  }, [userLocation, issueType, allProviders, isLoading]); 

  if (isLoading && displayedProviders.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center p-10 text-muted-foreground w-full flex-grow">
        <Loader2 className="h-12 w-12 animate-spin text-primary mb-4" />
        <p className="text-lg font-medium">Loading providers...</p>
        <p className="text-sm">Please wait a moment.</p>
      </div>
    );
  }
  
  return (
    <Card className="w-full max-w-3xl mx-auto shadow-xl flex flex-col flex-grow">
      <CardHeader className="flex-shrink-0">
        <CardTitle className="text-2xl flex items-center">
            <ListFilter className="mr-2 h-6 w-6 text-primary"/>
            Available Service Providers
        </CardTitle>
        {noSpecificMatch ? (
           <CardDescription className="text-sm">
            No providers specifically listed for "{issueType || 'your issue'}" {userLocation ? 'nearby' : ''}. 
            Showing all available providers.
          </CardDescription>
        ) : (
          <CardDescription className="text-sm">
            Showing providers {issueType ? `that can handle "${issueType}"` : ''} {userLocation ? 'sorted by distance.' : 'sorted by estimated arrival time.'}
          </CardDescription>
        )}
         {userLocation && (
          <p className="text-xs text-muted-foreground mt-1 flex items-center">
            <MapPinned className="mr-1.5 h-3.5 w-3.5" /> Your location: {userLocation.lat.toFixed(3)}, {userLocation.lng.toFixed(3)}
          </p>
        )}
      </CardHeader>
      <CardContent className="flex-grow flex flex-col min-h-0">
        {displayedProviders.length === 0 && !isLoading ? (
            <Alert variant="default" className="mt-4">
              <SearchX className="h-5 w-5" />
              <AlertTitle className="font-semibold">No Providers Found</AlertTitle>
              <AlertDescription>
                Unfortunately, we couldn't find any providers at this time matching your criteria.
              </AlertDescription>
            </Alert>
        ) : (
          <ScrollArea className="h-full pr-3">
            <div className="space-y-4">
              {displayedProviders.map((provider) => (
                <ProviderCard key={provider.id} provider={provider} onSelectProvider={onSelectProvider} />
              ))}
            </div>
          </ScrollArea>
        )}
      </CardContent>
    </Card>
  );
};

export default ProviderList;
