
// This file is generated by Firebase Studio.
"use client";

import type { FC } from 'react';
import { useState, useEffect } from 'react';
import ProviderCard from './ProviderCard';
import type { ServiceProvider, Location as UserLocationType } from '@/types';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { SearchX, Loader2, ListFilter, MapPinned } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';

// Mock data for Auto Xpress garages in Uganda
const MOCK_PROVIDERS: ServiceProvider[] = [
  // Kampala Area
  { 
    id: 'ax-kampala-central', 
    name: 'Auto Xpress - Kampala Central', 
    phone: '(256) 772-123456', 
    etaMinutes: 15, 
    currentLocation: { lat: 0.3136, lng: 32.5811 }, 
    generalLocation: "Kampala Central (City Oil Kira Rd)",
    servicesOffered: ['Tire Services', 'Battery Replacement', 'Oil Change', 'Brake Services', 'Flat tire', 'Dead battery', 'Vehicle Diagnostics'] 
  },
  { 
    id: 'ax-lugogo', 
    name: 'Auto Xpress - Lugogo', 
    phone: '(256) 772-234567', 
    etaMinutes: 20, 
    currentLocation: { lat: 0.3270, lng: 32.5990 }, // Adjusted approx location for Lugogo Bypass U-Save
    generalLocation: "Lugogo (U-Save, Next to Forest Mall)",
    servicesOffered: ['Suspension Work', 'Diagnostics', 'Tire Alignment', 'Jump Start', 'Engine failure', 'Car Wash'] 
  },
  { 
    id: 'ax-ntinda', 
    name: 'Auto Xpress - Ntinda', 
    phone: '(256) 772-345678', 
    etaMinutes: 25, 
    currentLocation: { lat: 0.3450, lng: 32.6120 }, // Ntinda Strecher Road
    generalLocation: "Ntinda (Strecher Road)",
    servicesOffered: ['Fuel Delivery (Emergency)', 'Battery Testing', 'Tire Puncture Repair', 'Minor Mechanical Repairs', 'Lockout', 'Fuel delivery'] 
  },
  { 
    id: 'ax-acacia', 
    name: 'Auto Xpress - Acacia Mall', 
    phone: '(256) 772-456789', 
    etaMinutes: 18, 
    currentLocation: { lat: 0.3312, lng: 32.5900 }, // Acacia Mall Basement Parking
    generalLocation: "Kololo (Acacia Mall)",
    servicesOffered: ['Tire Sales & Fitting', 'Oil and Filter Change', 'Wiper Blade Replacement', 'Lockout Assistance (Limited)', 'Car Accessories'] 
  },
  { 
    id: 'ax-nakawa', 
    name: 'Auto Xpress - Nakawa', 
    phone: '(256) 772-678901', 
    etaMinutes: 22, 
    currentLocation: { lat: 0.3300, lng: 32.6150 }, // Shell Nakawa
    generalLocation: "Nakawa (Shell Select)",
    servicesOffered: ['Full Service Maintenance', 'Tire Balancing', 'Air Conditioning Recharge', 'Diagnostics', 'Engine failure', 'Wheel Alignment'] 
  },
  {
    id: 'ax-garden-city',
    name: 'Auto Xpress - Garden City',
    phone: '(256) 772-000111',
    etaMinutes: 12,
    currentLocation: { lat: 0.3178, lng: 32.5860 }, // Garden City Mall Basement
    generalLocation: "Kampala Central (Garden City Mall)",
    servicesOffered: ['Tire Services', 'Battery Check & Replacement', 'Oil Top-up', 'Wiper Blades']
  },
  {
    id: 'ax-village-mall',
    name: 'Auto Xpress - Village Mall',
    phone: '(256) 773-222333',
    etaMinutes: 28,
    currentLocation: { lat: 0.3500, lng: 32.6090 }, // Bugolobi, Village Mall
    generalLocation: "Bugolobi (Village Mall)",
    servicesOffered: ['Tire Sales', 'Battery Sales', 'Oil Change Services', 'Car Accessories']
  },
  {
    id: 'ax-metroplex-nalya',
    name: 'Auto Xpress - Metroplex Naalya',
    phone: '(256) 774-555666',
    etaMinutes: 35,
    currentLocation: { lat: 0.3670, lng: 32.6330 }, // Naalya, Metroplex Mall
    generalLocation: "Naalya (Metroplex Mall)",
    servicesOffered: ['Tire Fitting & Balancing', 'Battery Services', 'Oil Change', 'Car Care Products']
  },
  
  // Entebbe Area
  { 
    id: 'ax-entebbe-victoria-mall', 
    name: 'Auto Xpress - Victoria Mall Entebbe', 
    phone: '(256) 772-567890', 
    etaMinutes: 45, 
    currentLocation: { lat: 0.0530, lng: 32.4640 }, // Victoria Mall, Entebbe
    generalLocation: "Entebbe (Victoria Mall)",
    servicesOffered: ['Battery Jump Start', 'Tire Inflation & Repair', 'Fluid Top-up', 'Brake Pad Replacement', 'Flat tire', 'Oil Change'] 
  },
  { 
    id: 'ax-entebbe-shell', 
    name: 'Auto Xpress - Shell Entebbe Rd', 
    phone: '(256) 775-101010', 
    etaMinutes: 40, 
    currentLocation: { lat: 0.0650, lng: 32.4750 }, // Shell on main Entebbe Road
    generalLocation: "Entebbe Road (Shell)",
    servicesOffered: ['Tire Services', 'Battery Replacement', 'Oil Change', 'Quick Diagnostics'] 
  },

  // Mukono Area
   { 
    id: 'ax-mukono-sombe', 
    name: 'Auto Xpress - Mukono Sombe', 
    phone: '(256) 773-112233', 
    etaMinutes: 55, 
    currentLocation: { lat: 0.3550, lng: 32.7500 }, // Sombe Supermarket Mukono
    generalLocation: "Mukono Town (Sombe Supermarket)",
    servicesOffered: ['Tire Services', 'Battery Replacement', 'Minor Mechanical Repairs', 'Jump Start', 'Oil Change'] 
  },

  // Jinja Area
  { 
    id: 'ax-jinja-main-street', 
    name: 'Auto Xpress - Jinja Main Street', 
    phone: '(256) 774-445566', 
    etaMinutes: 90, 
    currentLocation: { lat: 0.4320, lng: 33.2030 }, // Main Street, Jinja
    generalLocation: "Jinja City (Main Street)",
    servicesOffered: ['Full Service Maintenance', 'Diagnostics', 'Tire Alignment', 'Brake Services', 'Suspension Checks'] 
  },
  // Other towns (Mbarara, Gulu - if AutoXpress expands there)
  {
    id: 'ax-mbarara-high-street',
    name: 'Auto Xpress - Mbarara High Street',
    phone: '(256) 776-777888',
    etaMinutes: 180, // Approx from Kampala
    currentLocation: { lat: -0.6070, lng: 30.6570 },
    generalLocation: "Mbarara (High Street)",
    servicesOffered: ['Tire Services', 'Battery Solutions', 'Oil Change', 'Basic Maintenance']
  }
];


interface ProviderListProps {
  userLocation: UserLocationType | null;
  issueType: string;
  onSelectProvider: (provider: ServiceProvider) => void;
}

function calculateDistance(loc1: UserLocationType, loc2: UserLocationType): number {
  const R = 6371; // Radius of the Earth in km
  const dLat = (loc2.lat - loc1.lat) * Math.PI / 180;
  const dLng = (loc2.lng - loc1.lng) * Math.PI / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(loc1.lat * Math.PI / 180) * Math.cos(loc2.lat * Math.PI / 180) *
    Math.sin(dLng / 2) * Math.sin(dLng / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

const ProviderList: FC<ProviderListProps> = ({ userLocation, issueType, onSelectProvider }) => {
  const [isLoading, setIsLoading] = useState(true);
  const [displayedProviders, setDisplayedProviders] = useState<ServiceProvider[]>([]);
  const [noSpecificMatch, setNoSpecificMatch] = useState(false);

  useEffect(() => {
    setIsLoading(true);
    setNoSpecificMatch(false);
    
    // Simulate API call or data fetching
    setTimeout(() => {
      let primaryFilteredProviders = MOCK_PROVIDERS;
      
      // Filter by service if issueType is provided
      if (issueType && issueType.trim() !== "") {
        const lowerIssueType = issueType.toLowerCase();
        primaryFilteredProviders = MOCK_PROVIDERS.filter(p => 
          p.servicesOffered.some(service => 
            service.toLowerCase().includes(lowerIssueType) || 
            lowerIssueType.includes(service.toLowerCase()) // Also check if query is part of a service
          )
        );
      }
      
      // Calculate distances and sort if userLocation is available
      if (userLocation) {
        primaryFilteredProviders = primaryFilteredProviders.map(p => ({
          ...p,
          distanceKm: calculateDistance(userLocation, p.currentLocation)
        })).sort((a,b) => (a.distanceKm ?? Infinity) - (b.distanceKm ?? Infinity));
      } else {
         // If no location, sort by ETA or name as a fallback
         primaryFilteredProviders = primaryFilteredProviders.map(p => ({ ...p, distanceKm: undefined })).sort((a,b) => a.etaMinutes - b.etaMinutes);
      }

      if (primaryFilteredProviders.length > 0) {
        setDisplayedProviders(primaryFilteredProviders);
      } else {
        // No providers match the specific issue type
        setNoSpecificMatch(true);
        // Fallback: show all providers, sorted by distance (if location available) or ETA
        let fallbackProviders = MOCK_PROVIDERS.map(p => userLocation ? ({...p, distanceKm: calculateDistance(userLocation, p.currentLocation)}) : ({...p, distanceKm: undefined}));
        if (userLocation) {
            fallbackProviders.sort((a,b) => (a.distanceKm ?? Infinity) - (b.distanceKm ?? Infinity));
        } else {
            fallbackProviders.sort((a,b) => a.etaMinutes - b.etaMinutes); // Default sort by ETA if no location
        }
        setDisplayedProviders(fallbackProviders);
      }
      setIsLoading(false);
    }, 1500); // Simulate network delay
  }, [userLocation, issueType]);

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center p-10 text-muted-foreground w-full flex-grow">
        <Loader2 className="h-12 w-12 animate-spin text-primary mb-4" />
        <p className="text-lg font-medium">Finding Auto Xpress garages...</p>
        <p className="text-sm">Please wait a moment.</p>
      </div>
    );
  }
  
  return (
    <Card className="w-full max-w-3xl mx-auto shadow-xl flex flex-col flex-grow">
      <CardHeader className="flex-shrink-0">
        <CardTitle className="text-2xl flex items-center">
            <ListFilter className="mr-2 h-6 w-6 text-primary"/>
            Available Auto Xpress Garages
        </CardTitle>
        {noSpecificMatch ? (
           <CardDescription className="text-sm">
            No Auto Xpress garages specifically listed for "{issueType || 'your issue'}" {userLocation ? 'nearby' : ''}. 
            Showing all available garages. You can check towns like Kampala, Entebbe, Mukono, Jinja, or Mbarara.
          </CardDescription>
        ) : (
          <CardDescription className="text-sm">
            Showing Auto Xpress garages {issueType ? `that can handle "${issueType}"` : ''} {userLocation ? 'sorted by distance.' : 'sorted by estimated arrival time.'}
          </CardDescription>
        )}
         {userLocation && (
          <p className="text-xs text-muted-foreground mt-1 flex items-center">
            <MapPinned className="mr-1.5 h-3.5 w-3.5" /> Your location: {userLocation.lat.toFixed(3)}, {userLocation.lng.toFixed(3)}
          </p>
        )}
      </CardHeader>
      <CardContent className="flex-grow flex flex-col min-h-0">
        {displayedProviders.length === 0 && !noSpecificMatch ? (
            <Alert variant="default" className="mt-4">
              <SearchX className="h-5 w-5" />
              <AlertTitle className="font-semibold">No Auto Xpress Garages Found</AlertTitle>
              <AlertDescription>
                Unfortunately, we couldn't find any Auto Xpress garages at this time matching your criteria. 
                Please try broadening your search or check back later.
              </AlertDescription>
            </Alert>
        ) : (
          <ScrollArea className="h-full pr-3">
            <div className="space-y-4">
              {displayedProviders.map((provider) => (
                <ProviderCard key={provider.id} provider={provider} onSelectProvider={onSelectProvider} />
              ))}
            </div>
          </ScrollArea>
        )}
      </CardContent>
    </Card>
  );
};

export default ProviderList;

    